name 'baseline-linux'
maintainer 'Robert D. Thurston'
maintainer_email 'rdt@alasconnect.com'
license 'All Rights Reserved'
description 'Installs/Configures baseline-linux'
long_description 'Installs/Configures baseline-linux'
version '0.1.0'
chef_version '>= 14.0'
